### ISSUE TITLE
What are these BasicType_Package and Engine_Package etc

### ISSUE THREAD

**Issue by itfoldy** [GLX-ILLUSION/Unreal-Internal-Base#1]
Dumper-7 doesn't give these type of files (BasicType_Package.cpp and etc), I'm unsure how you can make it work with Dumper-7's dumped SDK

**Comment by GLX-ILLUSION** [comment]
it works fine with dumper-7 read the dumper-7 how to use guide https://github.com/Encryqed/Dumper-7/blob/main/UsingTheSDK.md

you only need to change the uworld calling function and include the respective files
